apiVersion: v1 # Version of the API
kind: pod      # Kind of resource
metadata:      # Detail about the resource
  name: nginx  # name of the resource
  namespace: demo  # namespace or you can say the group of the resource
spec:              # specification
  containers:      # here you can pass the details of the container in list format whom you want to run
  - name:  nginx   # name of the container
  image: nginx:latest  # name of the image
  ports:               # ports
    - containerPort:  80  # which port it will use to run the container